name = "surge"
compatibility_date = "2024-09-02"
main = "worker/index.ts"

[vars]
JSON_BASE = "https://cdn.jsdelivr.net/gh/Sleepstars/Surge-Geosite-Enhance@main/dist/geosite-json"
# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "SRS_BUCKET"
# Change this to your actual R2 bucket name
bucket_name = "surge-srs"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
