name = "surge"
compatibility_date = "2024-09-02"
main = "worker/index.ts"

[vars]
# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "GEO_KV"
id = "5eb30a83af794fb68bc5ee45dea470a9"

[[r2_buckets]]
binding = "SRS_BUCKET"
# Change this to your actual R2 bucket name
bucket_name = "surge-srs"

[[d1_databases]]
binding = "DB"
database_name = "surge-srs"
database_id = "3ac86863-0414-48e7-8c87-5d9ca429c2b3"

# [ai]
# binding = "AI"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
