name: Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - main

jobs:
  build-geosite-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build geosite JSON from Loyalsoldier geosite.dat
        run: npm run build:geosite

      - name: Update README
        run: |
          cat README_template.md data_files.md > README.md

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Install sing-box CLI
        run: |
          set -eux
          go install -v github.com/sagernet/sing-box/cmd/sing-box@v1.12.1
          echo "${HOME}/go/bin" >> "$GITHUB_PATH"
          sing-box version

      - name: Build SRS rulesets
        run: npm run build:srs

      - name: Install AWS CLI v2
        run: |
          set -eux
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
          unzip -q /tmp/awscliv2.zip -d /tmp
          sudo /tmp/aws/install --update
          aws --version

      - name: Sync SRS to R2 (bulk)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
          AWS_EC2_METADATA_DISABLED: true
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          SRS_BUCKET_NAME: ${{ vars.SRS_BUCKET_NAME }}
        run: |
          set -eux
          ls -l dist/srs || true
          if [ -z "${SRS_BUCKET_NAME:-}" ]; then
            echo "SRS_BUCKET_NAME repo variable not set; skip upload" >&2
            exit 0
          fi
          aws --version
          ENDPOINT="https://${CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com"
          aws configure set default.s3.signature_version s3v4
          aws s3 sync dist/srs "s3://${SRS_BUCKET_NAME}/geosite" \
            --endpoint-url "$ENDPOINT" \
            --exact-timestamps \
            --no-progress

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Commit and push if necessary
        run: |
          set -e
          git add README.md
          git add index.json
          git add dist/geosite-json || true
          if ! git diff --staged --quiet; then
            git commit -m "[auto] Sync with upstream (geosite.dat → JSON)"
            git push
          else
            echo "No changes to commit"
          fi
