name: Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - main

jobs:
  build-geosite-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Fetch geosite.dat and compute SHA
        id: geosite
        run: |
          set -eux
          URL="https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
          curl -fsSL -o /tmp/geosite.dat "$URL"
          SHA=$(sha256sum /tmp/geosite.dat | cut -d ' ' -f1)
          echo "sha=$SHA" >> "$GITHUB_OUTPUT"

      - name: Restore cache (geosite JSON)
        id: cache-json
        uses: actions/cache@v4
        with:
          path: |
            dist/geosite-json
            index.json
            data_files.md
          key: geosite-json-${{ steps.geosite.outputs.sha }}

      - name: Build geosite JSON from Loyalsoldier geosite.dat
        if: steps.cache-json.outputs.cache-hit != 'true'
        env:
          GEO_DAT_PATH: /tmp/geosite.dat
        run: npm run build:geosite

      - name: Update README
        run: |
          cat README_template.md data_files.md > README.md

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Install sing-box CLI
        run: |
          set -eux
          go install -v github.com/sagernet/sing-box/cmd/sing-box@v1.12.1
          echo "${HOME}/go/bin" >> "$GITHUB_PATH"
          sing-box version

      - name: Restore cache (SRS)
        id: cache-srs
        uses: actions/cache@v4
        with:
          path: dist/srs
          key: srs-${{ steps.geosite.outputs.sha }}-${{ vars.SRS_FILTERS }}

      - name: Build SRS rulesets
        if: steps.cache-srs.outputs.cache-hit != 'true'
        env:
          SRS_FILTERS: ${{ vars.SRS_FILTERS }}
          SRS_CONCURRENCY: ${{ vars.SRS_CONCURRENCY }}
        run: npm run build:srs
      - name: Install AWS CLI v2
        run: |
          set -eux
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
          unzip -q /tmp/awscliv2.zip -d /tmp
          sudo /tmp/aws/install --update
          aws --version

      - name: Manifest incremental sync to R2
        if: steps.cache-json.outputs.cache-hit != 'true' || steps.cache-srs.outputs.cache-hit != 'true'
        env:
          # AWS CLI (S3) credentials for R2
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          # Provide either R2_S3_ENDPOINT or (recommended) account id to derive endpoint
          R2_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # R2_S3_ENDPOINT: ${{ vars.R2_S3_ENDPOINT }}
          R2_BUCKET: ${{ vars.SRS_BUCKET_NAME }}
          R2_CONCURRENCY: ${{ vars.SRS_CONCURRENCY }}
        run: |
          set -eux
          if [ -z "${R2_BUCKET:-}" ]; then
            echo "R2_BUCKET (vars.SRS_BUCKET_NAME) not set; skip upload" >&2
            exit 0
          fi
          npm run r2:sync

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Commit and push if necessary
        run: |
          set -e
          git add README.md
          if ! git diff --staged --quiet; then
            git commit -m "[auto] Sync with upstream (geosite.dat → JSON)"
            git push
          else
            echo "No changes to commit"
          fi
